deployment:
  tasks:
    - export DEPLOY_DIR=/home/irmmaquinarias/repositories/irm_maquinarias
    - cd $DEPLOY_DIR
    - git reset --hard
    - git pull origin maestro
    - if [ ! -f .env ]; then cp .env.example .env; fi
    - composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    - if [ -f package.json ]; then npm ci && npm run production || npm run build || true; fi
    - php artisan key:generate --force || true
    - php artisan migrate --force || true
    - php artisan config:cache || true
    - php artisan route:cache || true
    - chown -R irmmaquinarias:irmmaquinarias storage bootstrap/cache || true
    - chmod -R 775 storage bootstrap/cache || true
    - rsync -a --delete ./public/ /home/irmmaquinarias/public_html/